GRID_SIZE = 80
PADDING_SIZE = 20  # number of cells to pad around a point in grid
ANGLE_INCREMENT = 5
MIN_DISTANCE_TO_INTERPOLATE = 10  # cm
TF_MODEL = "efficientdet_lite0.tflite"
CAMERA_ID = 0
FRAME_WIDTH = 640
FRAME_HEIGHT = 480
NUM_THREADS = 4
ENABLE_TPU = False
